## Encoding On training and testing data

In [1]:
#pip install category_encoders

In [2]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder
from category_encoders import HashingEncoder

### Loading the Train and test datasets after Feature Extraction

In [3]:
train = pd.read_csv("../data/train_features.csv")
test = pd.read_csv("../data/test_features.csv")

In [4]:
train.head()

,URL,Label,url_length,num_dots,num_hyphens,has_at,has_https,has_ip,count_suspicious_words
0,www.cityoflaredo.com/airport/,legit,29,2,0,0,0,0,0
1,www.cs.umb.edu/~laur/ARMiner/,legit,29,3,0,0,0,0,0
2,imdb.com/name/nm1027430/bio,legit,27,1,0,0,0,0,0
3,seatplans.com/airlines/Air-Transat,legit,34,1,1,0,0,0,0
4,vehisdidnsu.ru/gate.php,phishing,23,2,0,0,0,0,0

In [5]:
test.head()

,URL,Label,url_length,num_dots,num_hyphens,has_at,has_https,has_ip,count_suspicious_words
0,tr7.datahost84.org/rrca.php?id=,phishing,31,3,0,0,0,0,0
1,samyinayeh.com/login.htm,phishing,24,2,0,0,0,0,1
2,paypal.us.cgi.bin.webscr.cmd.login.webapps.mpp...,phishing,142,14,0,0,0,0,1
3,phoenixafrica.biz/wp-content/themes/twentyelev...,phishing,76,2,1,0,0,0,0
4,www.techbomb.com/websafe/,legit,25,2,0,0,0,0,0

In [6]:
label_encoders = {}

# Loop through all columns and apply Label Encoding to object (categorical) columns
for col in train.columns:
    if train[col].dtype == 'object':
        le = LabelEncoder()
        
        # Combine train and test for consistent encoding
        combined_data = pd.concat([train[col], test[col]], axis=0)
        le.fit(combined_data)

        # Encode
        train[col] = le.transform(train[col])
        test[col] = le.transform(test[col])
        
        # Store encoder for future use (e.g., decoding)
        label_encoders[col] = le

In [7]:
# View results
print("Encoded train data sample:")
train.head()

print("\nEncoded test data sample:")
test.head()

Encoded train data sample:

Encoded test data sample:

,URL,Label,url_length,num_dots,num_hyphens,has_at,has_https,has_ip,count_suspicious_words
0,403345,1,31,3,0,0,0,0,0
1,351073,1,24,2,0,0,0,0,1
2,316423,1,142,14,0,0,0,0,1
3,321189,1,76,2,1,0,0,0,0
4,483175,0,25,2,0,0,0,0,0

### Save encoded datasets

In [8]:
# Save encoded datasets
train.to_csv("../data/train_encoded.csv", index=False)
test.to_csv("../data/test_encoded.csv", index=False)

In [9]:
train.head()

,URL,Label,url_length,num_dots,num_hyphens,has_at,has_https,has_ip,count_suspicious_words
0,452940,0,29,2,0,0,0,0,0
1,455349,0,29,3,0,0,0,0,0
2,210650,0,27,1,0,0,0,0,0
3,355689,0,34,1,1,0,0,0,0
4,422046,1,23,2,0,0,0,0,0

In [10]:
test.head()

,URL,Label,url_length,num_dots,num_hyphens,has_at,has_https,has_ip,count_suspicious_words
0,403345,1,31,3,0,0,0,0,0
1,351073,1,24,2,0,0,0,0,1
2,316423,1,142,14,0,0,0,0,1
3,321189,1,76,2,1,0,0,0,0
4,483175,0,25,2,0,0,0,0,0